import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderTheme from "@/provider/provider-theme";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BackToTop from "@/components/BackToTop";
import Title from "@/components/Title";
import Analytics from "@/plugins/analytics";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ProviderTheme>
				<body
					suppressHydrationWarning
					className={`${geistSans.variable} relative min-h-screen font-mono flex flex-col justify-between ${geistMono.variable} antialiased`}
				>
					<div className={"flex-1"}>
						<Header />
						<main
							className={
								"md:mb-12 mb-8 min-w-full prose md:prose-lg dark:prose-invert"
							}
						>
							<Title />
							{children}
						</main>
						<Footer />
					</div>
					<BackToTop />
					<Analytics />
				</body>
			</ProviderTheme>
		</html>
	);
}
